baseurl = "https://plasma-team.github.io/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "bhrdn"
title = "Plasma Team"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Plasma Team"
copyright = "Copyright © 2018 Plasma Team"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "plasma-team"
email = "abuse@domain.com"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false